import React, { createContext, useContext, useState, useCallback } from "react";

export type Language = "en" | "pt";

const translations = {
  en: {
    // Common
    signOut: "Sign Out",
    signIn: "Sign In",
    signingIn: "Signing in...",
    dashboard: "Dashboard",
    breeding: "Breeding",
    hatchery: "Hatchery",
    nursery: "Nursery",
    farmers: "Farmers",
    processing: "Processing",
    inventory: "Inventory",
    finance: "Finance",
    analytics: "Analytics",
    alerts: "Alerts",
    update: "Update",
    tasks: "Tasks",
    aquaBot: "AquaBot",
    notifications: "Notifications",
    today: "Today",
    upcoming: "Upcoming",
    status: "Status",
    date: "Date",
    done: "Done",
    pending: "Pending",
    paid: "Paid",
    active: "active",
    inactive: "inactive",
    good: "Good",
    warning: "Warning",
    excellent: "Excellent",
    critical: "Critical",
    ok: "ok",
    low: "low",

    // Login
    welcomeBack: "Welcome back",
    signInDesc: "Sign in to your account to continue",
    emailAddress: "Email Address",
    enterEmail: "Enter your email",
    password: "Password",
    enterPassword: "Enter your password",
    loginFailed: "Login Failed",
    invalidCredentials: "Invalid email or password",
    loginHint: "Admin: aqua@gmail.com / Aqua@123 · Farmer: carlos@farm.com / farmer123",
    erpTagline: "Complete aquaculture management from breeding to market. Track every batch, manage farmers, and optimize your entire operation.",
    breedingLabel: "Breeding",
    growthLabel: "Growth",
    processingLabel: "Processing",

    // Admin Dashboard
    dashboardWelcome: "Welcome back! Here's your operation overview.",
    lastUpdated: "Last updated",
    activeBatches: "Active Batches",
    eggsThisMonth: "Eggs This Month",
    activeFarmers: "Active Farmers",
    processingToday: "Processing Today",
    avgSurvivalRate: "Avg Survival Rate",
    revenueMTD: "Revenue (MTD)",
    productionRevenueTrends: "Production & Revenue Trends",
    fishByStage: "Fish by Stage",
    fcrTrend: "FCR Trend",
    mortalityTrendCount: "Mortality Trend (count)",
    topFarmers: "🏆 Top Farmers",
    waterQuality: "Water Quality",
    recentActivity: "Recent Activity",
    recentAlerts: "Recent Alerts",
    productionKg: "Production (kg)",
    revenueK: "Revenue (R$K)",

    // Breeding
    breedingManagement: "Breeding Management",
    breedingDesc: "Broodstock tracking, egg production, and genetics",
    activeBroodstock: "Active Broodstock",
    avgHatchRate: "Avg Hatch Rate",
    nextSpawnCycle: "Next Spawn Cycle",
    days: "days",
    eggProductionHatchRate: "Egg Production & Hatch Rate",
    strainDistribution: "Strain Distribution",
    broodstockRegistry: "Broodstock Registry",
    id: "ID",
    strain: "Strain",
    age: "Age",
    weight: "Weight",
    eggs: "Eggs",
    months: "months",
    resting: "Resting",
    conditioning: "Conditioning",

    // Hatchery
    hatcheryModule: "Hatchery Module",
    hatcheryDesc: "Tank management, survival tracking, and feeding schedules",
    activeTanks: "Active Tanks",
    totalLarvae: "Total Larvae",
    avgSurvival: "Avg Survival",
    avgTemp: "Avg Temp",
    survivalRateCurve: "Survival Rate Curve",
    feedingScheduleToday: "Feeding Schedule Today",
    tankStatus: "Tank Status",
    tank: "Tank",
    species: "Species",
    stage: "Stage",
    count: "Count",
    temp: "Temp",
    survival: "Survival",
    daysLeft: "Days Left",

    // Nursery
    nurseryModule: "Nursery Module",
    nurseryDesc: "Batch tracking, growth logs, and transfer management",
    totalFry: "Total Fry",
    avgGrowth: "Avg Growth",
    readyToTransfer: "Ready to Transfer",
    growthCurve: "Growth Curve (Avg Weight g)",
    recentTransfers: "Recent Transfers",
    nurseryBatches: "Nursery Batches",
    batch: "Batch",
    source: "Source",
    pond: "Pond",
    avgWt: "Avg Wt",
    growth: "Growth",

    // Processing
    processingModule: "Processing Module",
    processingDesc: "Intake records, quality control, output tracking, waste analysis",
    todaysIntake: "Today's Intake",
    outputProducts: "Output Products",
    yieldRate: "Yield Rate",
    waste: "Waste",
    weeklyIntakeVsOutput: "Weekly Intake vs Output (kg)",
    qualityGradeDistribution: "Quality Grade Distribution",
    recentProcessingBatches: "Recent Processing Batches",
    intake: "Intake (kg)",
    output: "Output (kg)",
    yieldPercent: "Yield",
    grade: "Grade",

    // Inventory
    inventorySystem: "Inventory System",
    inventoryDesc: "Feed & medicine tracking with auto low-stock alerts",
    feedItems: "Feed Items",
    medicineItems: "Medicine Items",
    lowStockAlerts: "Low Stock Alerts",
    monthlySpend: "Monthly Spend",
    feedStockLevels: "Feed Stock Levels",
    medicineInventory: "Medicine Inventory",
    feedConsumptionTrend: "Feed Consumption Trend (kg)",
    expires: "Expires",
    belowReorderLevel: "Below reorder level",

    // Finance
    financeModule: "Finance Module",
    financeDesc: "Cost tracking, farmer payments, and profit reports",
    monthlyRevenue: "Monthly Revenue",
    monthlyExpenses: "Monthly Expenses",
    netProfit: "Net Profit",
    farmerPayments: "Farmer Payments",
    revenueVsExpenses: "Revenue vs Expenses (R$)",
    expenseBreakdown: "Expense Breakdown",
    farmerPaymentLedger: "Farmer Payment Ledger",
    farmer: "Farmer",
    period: "Period",
    amount: "Amount",
    feed: "Feed",
    labor: "Labor",
    medicine: "Medicine",
    transport: "Transport",
    utilities: "Utilities",
    other: "Other",

    // Analytics
    analyticsDashboard: "Analytics Dashboard",
    analyticsDesc: "Deep insights into mortality, growth, FCR, ROI, and farmer performance",
    avgMortality: "Avg Mortality",
    avgFCR: "Avg FCR",
    roiThisMonth: "ROI This Month",
    topFarmerScore: "Top Farmer Score",
    mortalityRateTrend: "Mortality Rate Trend (%)",
    fcrImprovement: "FCR Improvement",
    roiTrend: "ROI Trend (%)",
    farmerPerformanceRankings: "🏆 Farmer Performance Rankings",
    rank: "Rank",
    ponds: "Ponds",
    production: "Production",
    mortality: "Mortality",
    score: "Score",

    // Alerts
    alertsNotifications: "Alerts & Notifications",
    alertsDesc: "System-wide alerts for feed, disease, harvest, and operations",
    warnings: "Warnings",
    info: "Info",
    resolved: "Resolved",
    allAlerts: "All Alerts",

    // Farmer Dashboard
    hello: "Hello",
    farmOverviewToday: "Here's your farm overview for today",
    sunny: "Sunny",
    activePonds: "Active Ponds",
    allHealthy: "All healthy",
    currentStock: "Current Stock",
    thisWeek: "this week",
    avgWaterTemp: "Avg Water Temp",
    withinRange: "Within range",
    target: "Target",
    fishGrowth: "Fish Growth (g)",
    weeklyFeed: "Weekly Feed (kg)",
    pondHealthMonitor: "🐟 Pond Health Monitor",
    fish: "fish",
    todaysTasks: "Today's Tasks",
    recentUpdates: "Recent Updates",
    yourPerformance: "📊 Your Performance",
    performanceScore: "Performance Score",
    feedEfficiency: "Feed Efficiency",
    taskCompletion: "Task Completion",
    reportAccuracy: "Report Accuracy",

    // Daily Update
    dailyUpdate: "Daily Update",
    submitDailyReport: "Submit your daily farm report",
    todaysReport: "Today's Report",
    pondId: "Pond ID",
    feedKg: "Feed (kg)",
    mortalityLabel: "Mortality",
    tempC: "Temp (°C)",
    doMgL: "DO (mg/L)",
    phLevel: "pH Level",
    notesObservations: "Notes & Observations",
    notesPlaceholder: "Any observations, issues, behavioral changes...",
    uploadPhotos: "Upload Photos",
    dailyPondCondition: "Daily pond condition",
    uploadVideo: "Upload Video",
    feedingMedicine: "Feeding / medicine",
    submitDailyUpdate: "Submit Daily Update",
    updateSubmitted: "✅ Update Submitted",
    updateSubmittedDesc: "Your daily update has been recorded successfully",
    pastSubmissions: "Past Submissions",
    approved: "Approved",
    reviewed: "Reviewed",
    mort: "Mort.",

    // Tasks
    tasksTitle: "Tasks",
    tasksDesc: "Your assigned tasks and deadlines",
    complete: "Complete",
    morningFeedingAllPonds: "Morning feeding for all ponds",
    recordWaterQuality: "Record water quality parameters",
    uploadDailyPhotos: "Upload daily pond photos",
    eveningFeedingAdjust: "Evening feeding — adjust for Pond B2 temp",
    recordMortalityCount: "Record mortality count for all ponds",
    checkAerator: "Check aerator in Pond B2",
    submitWeeklyReport: "Submit weekly harvest report",
    medicineApplication: "Medicine application — Pond B2",
    feeding: "Feeding",
    monitoring: "Monitoring",
    reporting: "Reporting",
    maintenance: "Maintenance",
    health: "Health",

    // Notifications
    notificationsTitle: "Notifications",
    notificationsDesc: "Stay updated with your farm alerts",
    new: "new",
    waterTempAlert: "Water Temperature Alert",
    waterTempAlertMsg: "Pond B2 temperature reached 31.2°C — above safe threshold. Reduce feeding and check aerator.",
    feedDeliveryScheduled: "Feed Delivery Scheduled",
    feedDeliveryMsg: "500kg floating pellets arriving tomorrow at 9 AM. Please ensure storage area is ready.",
    paymentProcessed: "Payment Processed",
    paymentProcessedMsg: "R$85,000 has been credited to your account for March production.",
    reportReviewed: "Report Reviewed",
    reportReviewedMsg: "Your weekly report for Week 12 has been reviewed and approved by admin.",
    harvestScheduled: "Harvest Scheduled",
    harvestScheduledMsg: "Pond B2 harvest planned for Friday. Estimated yield: 1,200 kg. Stop feeding 24h before.",
    newBatchAllocated: "New Batch Allocated",
    newBatchAllocatedMsg: "Batch NB-2405: 5,000 fry transferred to your Pond C1 from nursery. Monitor closely.",
    weatherAdvisory: "Weather Advisory",
    weatherAdvisoryMsg: "Heatwave expected next week. Temperatures may exceed 35°C. Prepare shade nets and increase aeration.",
    medicineReminder: "Medicine Application Reminder",
    medicineReminderMsg: "Scheduled Oxytetracycline treatment for Pond B2 tomorrow at 8 AM. Follow dosage instructions.",
    trainingAvailable: "Training Module Available",
    trainingAvailableMsg: "New training video on FCR optimization is available. Watch it in the Resources section.",

    // AquaBot
    aquaBotTitle: "AquaBot",
    aquaBotDesc: "Your AI assistant for aquaculture queries",
    aquaBotWelcome: "Hello! 👋 I'm **AquaBot**, your AI aquaculture assistant.\n\nAsk me anything about fish farming — water quality, feeding, disease management, or best practices.\n\nYou can also try the quick questions below!",
    askPlaceholder: "Ask about water quality, feeding, diseases...",
    quickQ1: "What is ideal water temperature for tilapia?",
    quickQ2: "How to reduce FCR?",
    quickQ3: "Signs of fish disease?",
    quickQ4: "Best feeding schedule?",

    // Farmer Management
    farmerManagement: "Farmer Management",
    farmersRegistered: "farmers registered",
    addFarmer: "Add Farmer",
    farmerCreated: "Farmer Created!",
    addNewFarmer: "Add New Farmer",
    shareCredentials: "Share these credentials with",
    email: "Email",
    phone: "Phone",
    fullName: "Full Name",
    farmerName: "Farmer name",
    location: "Location",
    stateRegion: "State/Region",
    initialPassword: "Initial Password",
    createFarmerAccount: "Create Farmer Account",
    copyCredentials: "Copy Credentials",
    copied: "Copied!",
    credentialsCopied: "Login credentials copied to clipboard",
    error: "Error",
    nameEmailRequired: "Name and email are required",
    farmerAdded: "Farmer Added",
    credentialsReady: "Credentials ready to share with",
    joined: "Joined",

    // Dashboard specific
    farmerDailyUpdate: "Farmer daily update submitted",
    newBatchStarted: "New batch started in Hatchery T-01",
    processingBatchCompleted: "Processing batch PB-501 completed",
    feedDeliveryReceived: "Feed delivery received — 500kg",
    farmerPaymentProcessedDash: "Farmer payment processed — R$85,000",
    highMortalityAlert: "High mortality detected in Batch #1247 — 8% in 24h",
    lowFeedStockAlert: "Low feed stock: Micro Pellets at 12kg (below 15kg reorder)",
    waterTempSpikeAlert: "Water temp spike in Pond P-7 — 31.2°C",
    harvestScheduledAlert: "Harvest scheduled for Pond B2 tomorrow — est. 1,200 kg",
    batchTransferredAlert: "Batch NB-2399 transferred: 9,200 fry to Farm Pond P-3",

    // Farmer Dashboard specific
    newFeedDelivery: "New feed delivery arriving tomorrow — 500kg",
    waterTempAboveThreshold: "⚠ Water temp above threshold in Pond B2",
    weeklyReportReviewed: "Weekly report reviewed by admin ✓",
    harvestScheduledPondB2: "Harvest scheduled for Pond B2 — Friday",
    paymentProcessedAmount: "Payment R$85,000 processed successfully",
    morningFeedingTask: "Morning feeding - All ponds",
    waterQualityCheck: "Water quality check",
    uploadDailyPhotosTask: "Upload daily photos",
    eveningFeedingTask: "Evening feeding - All ponds",
    recordMortalityTask: "Record mortality count",
  },

  pt: {
    // Common
    signOut: "Sair",
    signIn: "Entrar",
    signingIn: "Entrando...",
    dashboard: "Painel",
    breeding: "Reprodução",
    hatchery: "Incubatório",
    nursery: "Berçário",
    farmers: "Produtores",
    processing: "Processamento",
    inventory: "Estoque",
    finance: "Financeiro",
    analytics: "Análises",
    alerts: "Alertas",
    update: "Atualizar",
    tasks: "Tarefas",
    aquaBot: "AquaBot",
    notifications: "Notificações",
    today: "Hoje",
    upcoming: "Próximas",
    status: "Status",
    date: "Data",
    done: "Concluído",
    pending: "Pendente",
    paid: "Pago",
    active: "ativo",
    inactive: "inativo",
    good: "Bom",
    warning: "Alerta",
    excellent: "Excelente",
    critical: "Crítico",
    ok: "ok",
    low: "baixo",

    // Login
    welcomeBack: "Bem-vindo de volta",
    signInDesc: "Entre na sua conta para continuar",
    emailAddress: "Endereço de E-mail",
    enterEmail: "Digite seu e-mail",
    password: "Senha",
    enterPassword: "Digite sua senha",
    loginFailed: "Falha no Login",
    invalidCredentials: "E-mail ou senha inválidos",
    loginHint: "Admin: aqua@gmail.com / Aqua@123 · Produtor: carlos@farm.com / farmer123",
    erpTagline: "Gestão completa de aquicultura da reprodução ao mercado. Rastreie cada lote, gerencie produtores e otimize toda sua operação.",
    breedingLabel: "Reprodução",
    growthLabel: "Crescimento",
    processingLabel: "Processamento",

    // Admin Dashboard
    dashboardWelcome: "Bem-vindo! Aqui está a visão geral da sua operação.",
    lastUpdated: "Última atualização",
    activeBatches: "Lotes Ativos",
    eggsThisMonth: "Ovos Este Mês",
    activeFarmers: "Produtores Ativos",
    processingToday: "Processamento Hoje",
    avgSurvivalRate: "Taxa de Sobrevivência",
    revenueMTD: "Receita (Mês)",
    productionRevenueTrends: "Tendências de Produção & Receita",
    fishByStage: "Peixes por Estágio",
    fcrTrend: "Tendência TCA",
    mortalityTrendCount: "Tendência de Mortalidade",
    topFarmers: "🏆 Melhores Produtores",
    waterQuality: "Qualidade da Água",
    recentActivity: "Atividade Recente",
    recentAlerts: "Alertas Recentes",
    productionKg: "Produção (kg)",
    revenueK: "Receita (R$K)",

    // Breeding
    breedingManagement: "Gestão de Reprodução",
    breedingDesc: "Rastreamento de reprodutores, produção de ovos e genética",
    activeBroodstock: "Reprodutores Ativos",
    avgHatchRate: "Taxa de Eclosão",
    nextSpawnCycle: "Próximo Ciclo",
    days: "dias",
    eggProductionHatchRate: "Produção de Ovos & Taxa de Eclosão",
    strainDistribution: "Distribuição por Linhagem",
    broodstockRegistry: "Registro de Reprodutores",
    id: "ID",
    strain: "Linhagem",
    age: "Idade",
    weight: "Peso",
    eggs: "Ovos",
    months: "meses",
    resting: "Descanso",
    conditioning: "Condicionamento",

    // Hatchery
    hatcheryModule: "Módulo de Incubatório",
    hatcheryDesc: "Gestão de tanques, rastreamento de sobrevivência e cronogramas de alimentação",
    activeTanks: "Tanques Ativos",
    totalLarvae: "Total de Larvas",
    avgSurvival: "Sobrevivência Média",
    avgTemp: "Temp. Média",
    survivalRateCurve: "Curva de Sobrevivência",
    feedingScheduleToday: "Cronograma de Alimentação Hoje",
    tankStatus: "Status dos Tanques",
    tank: "Tanque",
    species: "Espécie",
    stage: "Estágio",
    count: "Quantidade",
    temp: "Temp",
    survival: "Sobrevivência",
    daysLeft: "Dias Rest.",

    // Nursery
    nurseryModule: "Módulo Berçário",
    nurseryDesc: "Rastreamento de lotes, registros de crescimento e gestão de transferências",
    totalFry: "Total de Alevinos",
    avgGrowth: "Crescimento Médio",
    readyToTransfer: "Prontos p/ Transferir",
    growthCurve: "Curva de Crescimento (Peso Médio g)",
    recentTransfers: "Transferências Recentes",
    nurseryBatches: "Lotes do Berçário",
    batch: "Lote",
    source: "Origem",
    pond: "Tanque",
    avgWt: "Peso Méd.",
    growth: "Crescimento",

    // Processing
    processingModule: "Módulo de Processamento",
    processingDesc: "Registros de entrada, controle de qualidade, rastreamento de produção, análise de resíduos",
    todaysIntake: "Entrada Hoje",
    outputProducts: "Produtos Finais",
    yieldRate: "Rendimento",
    waste: "Resíduos",
    weeklyIntakeVsOutput: "Entrada vs Saída Semanal (kg)",
    qualityGradeDistribution: "Distribuição por Classificação",
    recentProcessingBatches: "Lotes de Processamento Recentes",
    intake: "Entrada (kg)",
    output: "Saída (kg)",
    yieldPercent: "Rendimento",
    grade: "Classe",

    // Inventory
    inventorySystem: "Sistema de Estoque",
    inventoryDesc: "Rastreamento de ração e medicamentos com alertas automáticos",
    feedItems: "Itens de Ração",
    medicineItems: "Itens de Medicamentos",
    lowStockAlerts: "Alertas de Estoque Baixo",
    monthlySpend: "Gasto Mensal",
    feedStockLevels: "Níveis de Estoque de Ração",
    medicineInventory: "Inventário de Medicamentos",
    feedConsumptionTrend: "Tendência de Consumo de Ração (kg)",
    expires: "Validade",
    belowReorderLevel: "Abaixo do nível de reposição",

    // Finance
    financeModule: "Módulo Financeiro",
    financeDesc: "Rastreamento de custos, pagamentos a produtores e relatórios de lucro",
    monthlyRevenue: "Receita Mensal",
    monthlyExpenses: "Despesas Mensais",
    netProfit: "Lucro Líquido",
    farmerPayments: "Pagamentos a Produtores",
    revenueVsExpenses: "Receita vs Despesas (R$)",
    expenseBreakdown: "Detalhamento de Despesas",
    farmerPaymentLedger: "Registro de Pagamentos",
    farmer: "Produtor",
    period: "Período",
    amount: "Valor",
    feed: "Ração",
    labor: "Mão de Obra",
    medicine: "Medicamentos",
    transport: "Transporte",
    utilities: "Utilidades",
    other: "Outros",

    // Analytics
    analyticsDashboard: "Painel de Análises",
    analyticsDesc: "Insights sobre mortalidade, crescimento, TCA, ROI e desempenho dos produtores",
    avgMortality: "Mortalidade Média",
    avgFCR: "TCA Médio",
    roiThisMonth: "ROI Este Mês",
    topFarmerScore: "Melhor Pontuação",
    mortalityRateTrend: "Tendência de Mortalidade (%)",
    fcrImprovement: "Melhoria do TCA",
    roiTrend: "Tendência ROI (%)",
    farmerPerformanceRankings: "🏆 Ranking de Desempenho dos Produtores",
    rank: "Posição",
    ponds: "Tanques",
    production: "Produção",
    mortality: "Mortalidade",
    score: "Pontuação",

    // Alerts
    alertsNotifications: "Alertas & Notificações",
    alertsDesc: "Alertas do sistema para ração, doenças, colheita e operações",
    warnings: "Avisos",
    info: "Informações",
    resolved: "Resolvidos",
    allAlerts: "Todos os Alertas",

    // Farmer Dashboard
    hello: "Olá",
    farmOverviewToday: "Aqui está a visão geral da sua fazenda hoje",
    sunny: "Ensolarado",
    activePonds: "Tanques Ativos",
    allHealthy: "Todos saudáveis",
    currentStock: "Estoque Atual",
    thisWeek: "esta semana",
    avgWaterTemp: "Temp. Média da Água",
    withinRange: "Dentro da faixa",
    target: "Meta",
    fishGrowth: "Crescimento (g)",
    weeklyFeed: "Ração Semanal (kg)",
    pondHealthMonitor: "🐟 Monitor de Saúde dos Tanques",
    fish: "peixes",
    todaysTasks: "Tarefas de Hoje",
    recentUpdates: "Atualizações Recentes",
    yourPerformance: "📊 Seu Desempenho",
    performanceScore: "Pontuação Geral",
    feedEfficiency: "Eficiência de Ração",
    taskCompletion: "Conclusão de Tarefas",
    reportAccuracy: "Precisão dos Relatórios",

    // Daily Update
    dailyUpdate: "Atualização Diária",
    submitDailyReport: "Envie seu relatório diário da fazenda",
    todaysReport: "Relatório de Hoje",
    pondId: "ID do Tanque",
    feedKg: "Ração (kg)",
    mortalityLabel: "Mortalidade",
    tempC: "Temp (°C)",
    doMgL: "OD (mg/L)",
    phLevel: "Nível de pH",
    notesObservations: "Notas & Observações",
    notesPlaceholder: "Observações, problemas, mudanças comportamentais...",
    uploadPhotos: "Enviar Fotos",
    dailyPondCondition: "Condição diária do tanque",
    uploadVideo: "Enviar Vídeo",
    feedingMedicine: "Alimentação / medicamento",
    submitDailyUpdate: "Enviar Atualização Diária",
    updateSubmitted: "✅ Atualização Enviada",
    updateSubmittedDesc: "Sua atualização diária foi registrada com sucesso",
    pastSubmissions: "Envios Anteriores",
    approved: "Aprovado",
    reviewed: "Revisado",
    mort: "Mort.",

    // Tasks
    tasksTitle: "Tarefas",
    tasksDesc: "Suas tarefas atribuídas e prazos",
    complete: "Concluído",
    morningFeedingAllPonds: "Alimentação matinal para todos os tanques",
    recordWaterQuality: "Registrar parâmetros de qualidade da água",
    uploadDailyPhotos: "Enviar fotos diárias dos tanques",
    eveningFeedingAdjust: "Alimentação vespertina — ajustar Tanque B2",
    recordMortalityCount: "Registrar contagem de mortalidade",
    checkAerator: "Verificar aerador no Tanque B2",
    submitWeeklyReport: "Enviar relatório semanal de colheita",
    medicineApplication: "Aplicação de medicamento — Tanque B2",
    feeding: "Alimentação",
    monitoring: "Monitoramento",
    reporting: "Relatórios",
    maintenance: "Manutenção",
    health: "Saúde",

    // Notifications
    notificationsTitle: "Notificações",
    notificationsDesc: "Fique atualizado com os alertas da sua fazenda",
    new: "novas",
    waterTempAlert: "Alerta de Temperatura da Água",
    waterTempAlertMsg: "Tanque B2 atingiu 31.2°C — acima do limite seguro. Reduza a alimentação e verifique o aerador.",
    feedDeliveryScheduled: "Entrega de Ração Agendada",
    feedDeliveryMsg: "500kg de ração flutuante chegando amanhã às 9h. Prepare a área de armazenamento.",
    paymentProcessed: "Pagamento Processado",
    paymentProcessedMsg: "R$85.000 foi creditado na sua conta referente à produção de março.",
    reportReviewed: "Relatório Revisado",
    reportReviewedMsg: "Seu relatório semanal da Semana 12 foi revisado e aprovado pelo administrador.",
    harvestScheduled: "Colheita Agendada",
    harvestScheduledMsg: "Colheita do Tanque B2 planejada para sexta-feira. Rendimento estimado: 1.200 kg. Pare a alimentação 24h antes.",
    newBatchAllocated: "Novo Lote Alocado",
    newBatchAllocatedMsg: "Lote NB-2405: 5.000 alevinos transferidos para seu Tanque C1 do berçário. Monitore de perto.",
    weatherAdvisory: "Aviso Meteorológico",
    weatherAdvisoryMsg: "Onda de calor esperada na próxima semana. Temperaturas podem ultrapassar 35°C. Prepare telas de sombra e aumente a aeração.",
    medicineReminder: "Lembrete de Aplicação de Medicamento",
    medicineReminderMsg: "Tratamento com Oxitetraciclina agendado para o Tanque B2 amanhã às 8h. Siga as instruções de dosagem.",
    trainingAvailable: "Módulo de Treinamento Disponível",
    trainingAvailableMsg: "Novo vídeo de treinamento sobre otimização de TCA disponível. Assista na seção de Recursos.",

    // AquaBot
    aquaBotTitle: "AquaBot",
    aquaBotDesc: "Seu assistente de IA para dúvidas sobre aquicultura",
    aquaBotWelcome: "Olá! 👋 Eu sou o **AquaBot**, seu assistente de IA para aquicultura.\n\nPergunte-me qualquer coisa sobre piscicultura — qualidade da água, alimentação, gestão de doenças ou melhores práticas.\n\nVocê também pode tentar as perguntas rápidas abaixo!",
    askPlaceholder: "Pergunte sobre qualidade da água, alimentação, doenças...",
    quickQ1: "Qual a temperatura ideal da água para tilápia?",
    quickQ2: "Como reduzir a TCA?",
    quickQ3: "Sinais de doença nos peixes?",
    quickQ4: "Melhor cronograma de alimentação?",

    // Farmer Management
    farmerManagement: "Gestão de Produtores",
    farmersRegistered: "produtores registrados",
    addFarmer: "Adicionar Produtor",
    farmerCreated: "Produtor Criado!",
    addNewFarmer: "Adicionar Novo Produtor",
    shareCredentials: "Compartilhe estas credenciais com",
    email: "E-mail",
    phone: "Telefone",
    fullName: "Nome Completo",
    farmerName: "Nome do produtor",
    location: "Localização",
    stateRegion: "Estado/Região",
    initialPassword: "Senha Inicial",
    createFarmerAccount: "Criar Conta do Produtor",
    copyCredentials: "Copiar Credenciais",
    copied: "Copiado!",
    credentialsCopied: "Credenciais copiadas para a área de transferência",
    error: "Erro",
    nameEmailRequired: "Nome e e-mail são obrigatórios",
    farmerAdded: "Produtor Adicionado",
    credentialsReady: "Credenciais prontas para compartilhar com",
    joined: "Ingressou",

    // Dashboard specific
    farmerDailyUpdate: "Atualização diária do produtor enviada",
    newBatchStarted: "Novo lote iniciado no Incubatório T-01",
    processingBatchCompleted: "Lote de processamento PB-501 concluído",
    feedDeliveryReceived: "Entrega de ração recebida — 500kg",
    farmerPaymentProcessedDash: "Pagamento do produtor processado — R$85.000",
    highMortalityAlert: "Alta mortalidade detectada no Lote #1247 — 8% em 24h",
    lowFeedStockAlert: "Estoque baixo: Micro Pellets a 12kg (abaixo de 15kg para reposição)",
    waterTempSpikeAlert: "Pico de temperatura no Tanque P-7 — 31.2°C",
    harvestScheduledAlert: "Colheita agendada para Tanque B2 amanhã — est. 1.200 kg",
    batchTransferredAlert: "Lote NB-2399 transferido: 9.200 alevinos para Tanque P-3",

    // Farmer Dashboard specific
    newFeedDelivery: "Nova entrega de ração amanhã — 500kg",
    waterTempAboveThreshold: "⚠ Temperatura acima do limite no Tanque B2",
    weeklyReportReviewed: "Relatório semanal revisado pelo admin ✓",
    harvestScheduledPondB2: "Colheita agendada para Tanque B2 — Sexta-feira",
    paymentProcessedAmount: "Pagamento R$85.000 processado com sucesso",
    morningFeedingTask: "Alimentação matinal - Todos os tanques",
    waterQualityCheck: "Verificação de qualidade da água",
    uploadDailyPhotosTask: "Enviar fotos diárias",
    eveningFeedingTask: "Alimentação vespertina - Todos os tanques",
    recordMortalityTask: "Registrar contagem de mortalidade",
  },
};

type TranslationKeys = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKeys) => string;
  toggleLanguage: () => void;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("pt");

  const t = useCallback((key: TranslationKeys): string => {
    return translations[language][key] || translations.en[key] || key;
  }, [language]);

  const toggleLanguage = useCallback(() => {
    setLanguage((prev) => (prev === "en" ? "pt" : "en"));
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
